### ISSUE TITLE
Expand the api metrics endpoint

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#499]
To add high level numbers along these lines (forgive my ugly yaml):  

````
-status_counts: 
       - production_count: 
       - organization_count:
- organization: 
  - backend_count: 
  - hits:
    - last_30_days_hits: 
    - last_month_hits: 
    - 2_months_ago_hits: 
  - unique_users:
    - last_30_days_unique_users:
    - last_month_unique_users:
    - 2_months_ago_unique_users:
  - average_response_time:
    - last_30_days_average_response_time:
    - last_month_average_response_time:
    - 2_months_ago_average_response_time:
````
